name:                net-mqtt-lens
version:             0.1.0.0
github:              "dustin/net-mqtt-lens"
license:             BSD3
author:              "Dustin Sallings"
maintainer:          "dustin@spy.net"
copyright:           "2020 Dustin Sallings"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Optics for net-mqtt
category:            Network

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dustin/net-mqtt-lens#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- net-mqtt >= 0.7.0.0 && < 0.8.0.0

library:
  source-dirs: src
  ghc-options:
    - -Wall

default-extensions:
  - OverloadedStrings
  - RecordWildCards
  - NamedFieldPuns

tests:
  net-mqtt-lens-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - net-mqtt-lens
    - HUnit
    - tasty
    - tasty-hunit
    - tasty-quickcheck
